package vista;
/**
 * @web http://www.jc-mouse.net/
 * @author Mouse
 */
public class interfaz extends javax.swing.JFrame {

    /** Creates new form interfaz */
    public interfaz() {
        initComponents();
        this.setTitle(" Proyecto Gestión de un Colegio ");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        btnPpalAlum = new javax.swing.JButton();
        btnPpalAulas = new javax.swing.JButton();
        btnPpalDoc = new javax.swing.JButton();
        btnPpalCursos = new javax.swing.JButton();
        panAlum = new javax.swing.JPanel();
        panTabAlum = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabAlumnos = new javax.swing.JTable();
        intDatPanAlum = new javax.swing.JPanel();
        etiDNI1 = new javax.swing.JLabel();
        etiNombre1 = new javax.swing.JLabel();
        etiApellidos1 = new javax.swing.JLabel();
        etiTelefono1 = new javax.swing.JLabel();
        etiCurso1 = new javax.swing.JLabel();
        txtDNI_Alum = new javax.swing.JFormattedTextField();
        txtNombre_Alum = new javax.swing.JFormattedTextField();
        txtApellidos_Alum = new javax.swing.JFormattedTextField();
        txtTelf_Alum = new javax.swing.JFormattedTextField();
        txtCurso_Alum = new javax.swing.JFormattedTextField();
        btnVerAlum = new javax.swing.JButton();
        btnMatricularAlum = new javax.swing.JButton();
        btnEliminarAlum = new javax.swing.JButton();
        btnModAlum = new javax.swing.JButton();
        panDoc = new javax.swing.JPanel();
        panTabDoc = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabDocentes = new javax.swing.JTable();
        intDatPanDoc = new javax.swing.JPanel();
        etiDNI2 = new javax.swing.JLabel();
        etiNombre2 = new javax.swing.JLabel();
        etiApellidos2 = new javax.swing.JLabel();
        etiTelefono2 = new javax.swing.JLabel();
        etiCurso2 = new javax.swing.JLabel();
        txtDNI_Doc = new javax.swing.JFormattedTextField();
        txtNombre_Doc = new javax.swing.JFormattedTextField();
        txtApellidos_Doc = new javax.swing.JFormattedTextField();
        txtTelf_Doc = new javax.swing.JFormattedTextField();
        txtCurso_Doc = new javax.swing.JFormattedTextField();
        btnVerDoc = new javax.swing.JButton();
        btnMatricularDoc = new javax.swing.JButton();
        btnEliminarDoc = new javax.swing.JButton();
        btnModDoc = new javax.swing.JButton();
        panAulas = new javax.swing.JPanel();
        panTabAulas = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tabAulas = new javax.swing.JTable();
        intDatPanAulas = new javax.swing.JPanel();
        etiIDAula = new javax.swing.JLabel();
        etiAforoAula = new javax.swing.JLabel();
        txtIDAula = new javax.swing.JFormattedTextField();
        txtAforoAula = new javax.swing.JFormattedTextField();
        btnVerAulas = new javax.swing.JButton();
        btnMatricularAulas = new javax.swing.JButton();
        btnEliminarAulas = new javax.swing.JButton();
        btnModAulas = new javax.swing.JButton();
        panCursos = new javax.swing.JPanel();
        panTabCursos = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tabCursos = new javax.swing.JTable();
        intDatPanCursos = new javax.swing.JPanel();
        etiDNI4 = new javax.swing.JLabel();
        etiNombre4 = new javax.swing.JLabel();
        etiApellidos4 = new javax.swing.JLabel();
        etiTelefono4 = new javax.swing.JLabel();
        txtIDCurso = new javax.swing.JFormattedTextField();
        txtNombreCurso = new javax.swing.JFormattedTextField();
        txtModalidadCurso = new javax.swing.JFormattedTextField();
        txtHorasCurso = new javax.swing.JFormattedTextField();
        btnVerCursos = new javax.swing.JButton();
        btnMatricularCursos = new javax.swing.JButton();
        btnEliminarCursos = new javax.swing.JButton();
        btnModCursos = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menArch = new javax.swing.JMenu();
        subMenSalir = new javax.swing.JMenuItem();
        menAcer = new javax.swing.JMenu();
        subMenVersion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "   Elige una opción  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11)));
        panPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPpalAlum.setText("Alumnos");
        panPrincipal.add(btnPpalAlum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 120));

        btnPpalAulas.setText("Aulas");
        panPrincipal.add(btnPpalAulas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 170, 120));

        btnPpalDoc.setText("Docentes");
        panPrincipal.add(btnPpalDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 20, 160, 120));

        btnPpalCursos.setText("Cursos");
        panPrincipal.add(btnPpalCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 150, 160, 120));

        panTabAlum.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "   Lista de Productos  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        tabAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tabAlumnos);

        javax.swing.GroupLayout panTabAlumLayout = new javax.swing.GroupLayout(panTabAlum);
        panTabAlum.setLayout(panTabAlumLayout);
        panTabAlumLayout.setHorizontalGroup(
            panTabAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTabAlumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panTabAlumLayout.setVerticalGroup(
            panTabAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTabAlumLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        intDatPanAlum.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "   Introducción de datos   ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        etiDNI1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        etiDNI1.setText("DNI");

        etiNombre1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        etiNombre1.setText("Nombre");

        etiApellidos1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        etiApellidos1.setText("Apellidos");

        etiTelefono1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        etiTelefono1.setText("Teléfono");

        etiCurso1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        etiCurso1.setText("Curso en el que se matricula");

        try {
            txtDNI_Alum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDNI_Alum.setText("        ");
        txtDNI_Alum.setToolTipText("DNI EN FORMATO ########");
        txtDNI_Alum.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDNI_Alum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNI_AlumActionPerformed(evt);
            }
        });

        try {
            txtNombre_Alum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("******************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNombre_Alum.setText("");
        txtNombre_Alum.setToolTipText("");
        txtNombre_Alum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre_AlumActionPerformed(evt);
            }
        });

        txtApellidos_Alum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtApellidos_Alum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidos_AlumActionPerformed(evt);
            }
        });

        txtTelf_Alum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        txtCurso_Alum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout intDatPanAlumLayout = new javax.swing.GroupLayout(intDatPanAlum);
        intDatPanAlum.setLayout(intDatPanAlumLayout);
        intDatPanAlumLayout.setHorizontalGroup(
            intDatPanAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intDatPanAlumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(intDatPanAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(intDatPanAlumLayout.createSequentialGroup()
                        .addGroup(intDatPanAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(intDatPanAlumLayout.createSequentialGroup()
                                .addComponent(etiTelefono1)
                                .addGap(18, 18, 18)
                                .addComponent(txtTelf_Alum, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(intDatPanAlumLayout.createSequentialGroup()
                                .addComponent(etiDNI1)
                                .addGap(18, 18, 18)
                                .addComponent(txtDNI_Alum, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(342, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, intDatPanAlumLayout.createSequentialGroup()
                        .addGroup(intDatPanAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(intDatPanAlumLayout.createSequentialGroup()
                                .addComponent(etiNombre1)
                                .addGap(40, 40, 40)
                                .addComponent(txtNombre_Alum))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, intDatPanAlumLayout.createSequentialGroup()
                                .addComponent(etiApellidos1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(txtApellidos_Alum, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41))
                    .addGroup(intDatPanAlumLayout.createSequentialGroup()
                        .addComponent(etiCurso1)
                        .addGap(18, 18, 18)
                        .addComponent(txtCurso_Alum, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        intDatPanAlumLayout.setVerticalGroup(
            intDatPanAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intDatPanAlumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(intDatPanAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiDNI1)
                    .addComponent(txtDNI_Alum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(intDatPanAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiNombre1)
                    .addComponent(txtNombre_Alum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(intDatPanAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiApellidos1)
                    .addComponent(txtApellidos_Alum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(intDatPanAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiTelefono1)
                    .addComponent(txtTelf_Alum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(intDatPanAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiCurso1)
                    .addComponent(txtCurso_Alum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnVerAlum.setText("Ver alumnos");
        btnVerAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerAlumActionPerformed(evt);
            }
        });

        btnMatricularAlum.setText("Matricular alumno");
        btnMatricularAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatricularAlumActionPerformed(evt);
            }
        });

        btnEliminarAlum.setText("Eliminar alumno");

        btnModAlum.setText("Modificar alumno");

        javax.swing.GroupLayout panAlumLayout = new javax.swing.GroupLayout(panAlum);
        panAlum.setLayout(panAlumLayout);
        panAlumLayout.setHorizontalGroup(
            panAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAlumLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(intDatPanAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panTabAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAlumLayout.createSequentialGroup()
                        .addComponent(btnVerAlum, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMatricularAlum, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarAlum, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModAlum, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
        );
        panAlumLayout.setVerticalGroup(
            panAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAlumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panTabAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(intDatPanAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVerAlum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModAlum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEliminarAlum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMatricularAlum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );

        panTabDoc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "   Lista de Productos  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        tabDocentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tabDocentes);

        javax.swing.GroupLayout panTabDocLayout = new javax.swing.GroupLayout(panTabDoc);
        panTabDoc.setLayout(panTabDocLayout);
        panTabDocLayout.setHorizontalGroup(
            panTabDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTabDocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panTabDocLayout.setVerticalGroup(
            panTabDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTabDocLayout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        intDatPanDoc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "   Introducción de datos   ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        etiDNI2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        etiDNI2.setText("DNI");

        etiNombre2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        etiNombre2.setText("Nombre");

        etiApellidos2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        etiApellidos2.setText("Apellidos");

        etiTelefono2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        etiTelefono2.setText("Teléfono");

        etiCurso2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        etiCurso2.setText("Curso en el que se matricula");

        try {
            txtDNI_Doc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDNI_Doc.setToolTipText("DNI EN FORMATO ########-A");
        txtDNI_Doc.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDNI_Doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNI_DocActionPerformed(evt);
            }
        });

        try {
            txtNombre_Doc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("******************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNombre_Doc.setText("");
        txtNombre_Doc.setToolTipText("");
        txtNombre_Doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre_DocActionPerformed(evt);
            }
        });

        txtApellidos_Doc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtApellidos_Doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidos_DocActionPerformed(evt);
            }
        });

        txtTelf_Doc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        txtCurso_Doc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout intDatPanDocLayout = new javax.swing.GroupLayout(intDatPanDoc);
        intDatPanDoc.setLayout(intDatPanDocLayout);
        intDatPanDocLayout.setHorizontalGroup(
            intDatPanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intDatPanDocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(intDatPanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(intDatPanDocLayout.createSequentialGroup()
                        .addGroup(intDatPanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(intDatPanDocLayout.createSequentialGroup()
                                .addComponent(etiTelefono2)
                                .addGap(18, 18, 18)
                                .addComponent(txtTelf_Doc, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(intDatPanDocLayout.createSequentialGroup()
                                .addComponent(etiDNI2)
                                .addGap(18, 18, 18)
                                .addComponent(txtDNI_Doc, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(342, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, intDatPanDocLayout.createSequentialGroup()
                        .addGroup(intDatPanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(intDatPanDocLayout.createSequentialGroup()
                                .addComponent(etiNombre2)
                                .addGap(40, 40, 40)
                                .addComponent(txtNombre_Doc))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, intDatPanDocLayout.createSequentialGroup()
                                .addComponent(etiApellidos2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(txtApellidos_Doc, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41))
                    .addGroup(intDatPanDocLayout.createSequentialGroup()
                        .addComponent(etiCurso2)
                        .addGap(18, 18, 18)
                        .addComponent(txtCurso_Doc, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        intDatPanDocLayout.setVerticalGroup(
            intDatPanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intDatPanDocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(intDatPanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiDNI2)
                    .addComponent(txtDNI_Doc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(intDatPanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiNombre2)
                    .addComponent(txtNombre_Doc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(intDatPanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiApellidos2)
                    .addComponent(txtApellidos_Doc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(intDatPanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiTelefono2)
                    .addComponent(txtTelf_Doc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(intDatPanDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiCurso2)
                    .addComponent(txtCurso_Doc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnVerDoc.setText("Ver alumnos");
        btnVerDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDocActionPerformed(evt);
            }
        });

        btnMatricularDoc.setText("Matricular alumno");
        btnMatricularDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatricularDocActionPerformed(evt);
            }
        });

        btnEliminarDoc.setText("Eliminar alumno");

        btnModDoc.setText("Modificar alumno");

        javax.swing.GroupLayout panDocLayout = new javax.swing.GroupLayout(panDoc);
        panDoc.setLayout(panDocLayout);
        panDocLayout.setHorizontalGroup(
            panDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDocLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(intDatPanDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panTabDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDocLayout.createSequentialGroup()
                        .addComponent(btnVerDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMatricularDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
        );
        panDocLayout.setVerticalGroup(
            panDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panTabDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(intDatPanDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVerDoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModDoc, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEliminarDoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMatricularDoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );

        panTabAulas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "   Lista de Productos  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        tabAulas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(tabAulas);

        javax.swing.GroupLayout panTabAulasLayout = new javax.swing.GroupLayout(panTabAulas);
        panTabAulas.setLayout(panTabAulasLayout);
        panTabAulasLayout.setHorizontalGroup(
            panTabAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTabAulasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panTabAulasLayout.setVerticalGroup(
            panTabAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTabAulasLayout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        intDatPanAulas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "   Introducción de datos   ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        etiIDAula.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        etiIDAula.setText("ID Aula");

        etiAforoAula.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        etiAforoAula.setText("Aforo");

        try {
            txtIDAula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIDAula.setText("        ");
        txtIDAula.setToolTipText("DNI EN FORMATO ########");
        txtIDAula.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtIDAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDAulaActionPerformed(evt);
            }
        });

        try {
            txtAforoAula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("******************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtAforoAula.setText("");
        txtAforoAula.setToolTipText("");
        txtAforoAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAforoAulaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout intDatPanAulasLayout = new javax.swing.GroupLayout(intDatPanAulas);
        intDatPanAulas.setLayout(intDatPanAulasLayout);
        intDatPanAulasLayout.setHorizontalGroup(
            intDatPanAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intDatPanAulasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(intDatPanAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(intDatPanAulasLayout.createSequentialGroup()
                        .addComponent(etiIDAula)
                        .addGap(18, 18, 18)
                        .addComponent(txtIDAula, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(352, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, intDatPanAulasLayout.createSequentialGroup()
                        .addComponent(etiAforoAula)
                        .addGap(40, 40, 40)
                        .addComponent(txtAforoAula)
                        .addGap(41, 41, 41))))
        );
        intDatPanAulasLayout.setVerticalGroup(
            intDatPanAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intDatPanAulasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(intDatPanAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiIDAula)
                    .addComponent(txtIDAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(intDatPanAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiAforoAula)
                    .addComponent(txtAforoAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnVerAulas.setText("Ver alumnos");
        btnVerAulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerAulasActionPerformed(evt);
            }
        });

        btnMatricularAulas.setText("Matricular alumno");
        btnMatricularAulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatricularAulasActionPerformed(evt);
            }
        });

        btnEliminarAulas.setText("Eliminar alumno");

        btnModAulas.setText("Modificar alumno");

        javax.swing.GroupLayout panAulasLayout = new javax.swing.GroupLayout(panAulas);
        panAulas.setLayout(panAulasLayout);
        panAulasLayout.setHorizontalGroup(
            panAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAulasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(intDatPanAulas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panTabAulas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAulasLayout.createSequentialGroup()
                        .addComponent(btnVerAulas, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMatricularAulas, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarAulas, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModAulas, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
        panAulasLayout.setVerticalGroup(
            panAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAulasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panTabAulas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(intDatPanAulas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVerAulas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModAulas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEliminarAulas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMatricularAulas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        panTabCursos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "   Lista de Productos  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        tabCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(tabCursos);

        javax.swing.GroupLayout panTabCursosLayout = new javax.swing.GroupLayout(panTabCursos);
        panTabCursos.setLayout(panTabCursosLayout);
        panTabCursosLayout.setHorizontalGroup(
            panTabCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTabCursosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panTabCursosLayout.setVerticalGroup(
            panTabCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTabCursosLayout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        intDatPanCursos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "   Introducción de datos   ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        etiDNI4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        etiDNI4.setText("ID Curso");

        etiNombre4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        etiNombre4.setText("Nombre");

        etiApellidos4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        etiApellidos4.setText("Modalidad");

        etiTelefono4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        etiTelefono4.setText("Horas");

        try {
            txtIDCurso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIDCurso.setToolTipText("ID DEL CURSO EN FORMATO NUMÉRICO");
        txtIDCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtIDCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDCursoActionPerformed(evt);
            }
        });

        try {
            txtNombreCurso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("******************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNombreCurso.setText("");
        txtNombreCurso.setToolTipText("");
        txtNombreCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCursoActionPerformed(evt);
            }
        });

        txtModalidadCurso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtModalidadCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModalidadCursoActionPerformed(evt);
            }
        });

        txtHorasCurso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout intDatPanCursosLayout = new javax.swing.GroupLayout(intDatPanCursos);
        intDatPanCursos.setLayout(intDatPanCursosLayout);
        intDatPanCursosLayout.setHorizontalGroup(
            intDatPanCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intDatPanCursosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(intDatPanCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(intDatPanCursosLayout.createSequentialGroup()
                        .addGroup(intDatPanCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(intDatPanCursosLayout.createSequentialGroup()
                                .addComponent(etiTelefono4)
                                .addGap(18, 18, 18)
                                .addComponent(txtHorasCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(intDatPanCursosLayout.createSequentialGroup()
                                .addComponent(etiDNI4)
                                .addGap(18, 18, 18)
                                .addComponent(txtIDCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(352, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, intDatPanCursosLayout.createSequentialGroup()
                        .addGroup(intDatPanCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(intDatPanCursosLayout.createSequentialGroup()
                                .addComponent(etiNombre4)
                                .addGap(40, 40, 40)
                                .addComponent(txtNombreCurso))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, intDatPanCursosLayout.createSequentialGroup()
                                .addComponent(etiApellidos4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(txtModalidadCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41))))
        );
        intDatPanCursosLayout.setVerticalGroup(
            intDatPanCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intDatPanCursosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(intDatPanCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiDNI4)
                    .addComponent(txtIDCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(intDatPanCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiNombre4)
                    .addComponent(txtNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(intDatPanCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiApellidos4)
                    .addComponent(txtModalidadCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(intDatPanCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiTelefono4)
                    .addComponent(txtHorasCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        btnVerCursos.setText("Ver alumnos");
        btnVerCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCursosActionPerformed(evt);
            }
        });

        btnMatricularCursos.setText("Matricular alumno");
        btnMatricularCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatricularCursosActionPerformed(evt);
            }
        });

        btnEliminarCursos.setText("Eliminar alumno");

        btnModCursos.setText("Modificar alumno");

        javax.swing.GroupLayout panCursosLayout = new javax.swing.GroupLayout(panCursos);
        panCursos.setLayout(panCursosLayout);
        panCursosLayout.setHorizontalGroup(
            panCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCursosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(intDatPanCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panTabCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCursosLayout.createSequentialGroup()
                        .addComponent(btnVerCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMatricularCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
        );
        panCursosLayout.setVerticalGroup(
            panCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCursosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panTabCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(intDatPanCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVerCursos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModCursos, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEliminarCursos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMatricularCursos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );

        menArch.setText("Archivo");

        subMenSalir.setText("Salir");
        menArch.add(subMenSalir);

        menuBar.add(menArch);

        menAcer.setText("Acerca de");

        subMenVersion.setText("Versión");
        menAcer.add(subMenVersion);

        menuBar.add(menAcer);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panAulas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panAulas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panPrincipal.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDNI_AlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNI_AlumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNI_AlumActionPerformed

    private void txtNombre_AlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre_AlumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre_AlumActionPerformed

    private void txtApellidos_AlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidos_AlumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidos_AlumActionPerformed

    private void btnVerAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAlumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerAlumActionPerformed

    private void btnMatricularAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatricularAlumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMatricularAlumActionPerformed

    private void txtDNI_DocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNI_DocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNI_DocActionPerformed

    private void txtNombre_DocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre_DocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre_DocActionPerformed

    private void txtApellidos_DocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidos_DocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidos_DocActionPerformed

    private void btnVerDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerDocActionPerformed

    private void btnMatricularDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatricularDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMatricularDocActionPerformed

    private void txtIDCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDCursoActionPerformed

    private void txtNombreCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCursoActionPerformed

    private void txtModalidadCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModalidadCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModalidadCursoActionPerformed

    private void btnVerCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerCursosActionPerformed

    private void btnMatricularCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatricularCursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMatricularCursosActionPerformed

    private void btnMatricularAulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatricularAulasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMatricularAulasActionPerformed

    private void btnVerAulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAulasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerAulasActionPerformed

    private void txtAforoAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAforoAulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAforoAulaActionPerformed

    private void txtIDAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDAulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDAulaActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEliminarAlum;
    public javax.swing.JButton btnEliminarAulas;
    public javax.swing.JButton btnEliminarCursos;
    public javax.swing.JButton btnEliminarDoc;
    public javax.swing.JButton btnMatricularAlum;
    public javax.swing.JButton btnMatricularAulas;
    public javax.swing.JButton btnMatricularCursos;
    public javax.swing.JButton btnMatricularDoc;
    private javax.swing.JButton btnModAlum;
    private javax.swing.JButton btnModAulas;
    private javax.swing.JButton btnModCursos;
    private javax.swing.JButton btnModDoc;
    private javax.swing.JButton btnPpalAlum;
    private javax.swing.JButton btnPpalAulas;
    private javax.swing.JButton btnPpalCursos;
    private javax.swing.JButton btnPpalDoc;
    public javax.swing.JButton btnVerAlum;
    public javax.swing.JButton btnVerAulas;
    public javax.swing.JButton btnVerCursos;
    public javax.swing.JButton btnVerDoc;
    private javax.swing.JLabel etiAforoAula;
    private javax.swing.JLabel etiApellidos1;
    private javax.swing.JLabel etiApellidos2;
    private javax.swing.JLabel etiApellidos4;
    private javax.swing.JLabel etiCurso1;
    private javax.swing.JLabel etiCurso2;
    private javax.swing.JLabel etiDNI1;
    private javax.swing.JLabel etiDNI2;
    private javax.swing.JLabel etiDNI4;
    private javax.swing.JLabel etiIDAula;
    private javax.swing.JLabel etiNombre1;
    private javax.swing.JLabel etiNombre2;
    private javax.swing.JLabel etiNombre4;
    private javax.swing.JLabel etiTelefono1;
    private javax.swing.JLabel etiTelefono2;
    private javax.swing.JLabel etiTelefono4;
    private javax.swing.JPanel intDatPanAlum;
    private javax.swing.JPanel intDatPanAulas;
    private javax.swing.JPanel intDatPanCursos;
    private javax.swing.JPanel intDatPanDoc;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JMenu menAcer;
    private javax.swing.JMenu menArch;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel panAlum;
    private javax.swing.JPanel panAulas;
    private javax.swing.JPanel panCursos;
    private javax.swing.JPanel panDoc;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JPanel panTabAlum;
    private javax.swing.JPanel panTabAulas;
    private javax.swing.JPanel panTabCursos;
    private javax.swing.JPanel panTabDoc;
    private javax.swing.JMenuItem subMenSalir;
    private javax.swing.JMenuItem subMenVersion;
    public javax.swing.JTable tabAlumnos;
    public javax.swing.JTable tabAulas;
    public javax.swing.JTable tabCursos;
    public javax.swing.JTable tabDocentes;
    public javax.swing.JFormattedTextField txtAforoAula;
    public javax.swing.JFormattedTextField txtApellidos_Alum;
    public javax.swing.JFormattedTextField txtApellidos_Doc;
    public javax.swing.JFormattedTextField txtCurso_Alum;
    public javax.swing.JFormattedTextField txtCurso_Doc;
    public javax.swing.JFormattedTextField txtDNI_Alum;
    public javax.swing.JFormattedTextField txtDNI_Doc;
    public javax.swing.JFormattedTextField txtHorasCurso;
    public javax.swing.JFormattedTextField txtIDAula;
    public javax.swing.JFormattedTextField txtIDCurso;
    public javax.swing.JFormattedTextField txtModalidadCurso;
    public javax.swing.JFormattedTextField txtNombreCurso;
    public javax.swing.JFormattedTextField txtNombre_Alum;
    public javax.swing.JFormattedTextField txtNombre_Doc;
    public javax.swing.JFormattedTextField txtTelf_Alum;
    public javax.swing.JFormattedTextField txtTelf_Doc;
    // End of variables declaration//GEN-END:variables

}
